spring:  
  profiles.active: common, logging-daily, local-a     # test 서버에 올리려고 packaging할 때  common, test, logging-daily 로 변경해야 한다.
                                                      # 그리고 Run Configurations에서 Goal에 package 를 넣고 Run 클릭.  

---

spring:
  profiles: common
  mvc:
    view:
      prefix: /WEB-INF/jsp/
      suffix: .jsp
  http:
    multipart:
      enabled: true
      max-file-size: 10Mb
      max-request-size: 10Mb
  thymeleaf:
    cache: false
  jpa:
    show-sql: true
    database: mysql
    hibernate:
      ddl-auto: none
      naming:
        physical-strategy: kr.sir.common.PrefixNamingStrategy

server:
  error:
    whitelabel:
      enabled: false

---

spring:
  profiles: logging-daily
  
logging:
  config: classpath:logback-spring.xml    

---

spring:
  profiles: local-g
  datasource:
     initialize: true
     url: "jdbc:mysql://localhost:3306/sirgjw?characterEncoding=utf8&useSSL=false&zeroDateTimeBehavior=convertToNull"
#     url: "jdbc:mysql://sirgjw.gnutest.com:3306/sirgjw?characterEncoding=utf8&useSSL=false&zeroDateTimeBehavior=convertToNull"
     username: "root"
     password: "8989"
     driver-class-name: com.mysql.jdbc.Driver
     
logging:
  file: logs/application.log
  level:
    org.springframework.boot: INFO
    org.springframework.web: INFO
    org.springframework.data: DEBUG
    kr.sir: DEBUG

path: 
  fileName: src/main/resources/config.yml
  
---

spring:
  profiles: local-a
  datasource:
     initialize: true
     url: "jdbc:mysql://localhost:3306/ahn?characterEncoding=utf8&useSSL=false&zeroDateTimeBehavior=convertToNull"
#     url: "jdbc:mysql://localhost:3316/ahn?characterEncoding=utf8&useSSL=false&zeroDateTimeBehavior=convertToNull"
     username: "ahn23"
     password: "qwer"
     driver-class-name: com.mysql.jdbc.Driver
     
logging:
  file: logs/application.log
  level:
    org.springframework.boot: INFO
    org.springframework.web: INFO
    org.springframework.data: DEBUG
    kr.sir: DEBUG

path: 
  fileName: src/main/resources/config.yml

---

spring:
  profiles: test
  datasource:
     initialize: true
     url: "jdbc:mysql://localhost:3306/sirjsp?characterEncoding=utf8&useSSL=false&zeroDateTimeBehavior=convertToNull"
     username: sirjsp
     password: sirjsp12
     driver-class-name: com.mysql.jdbc.Driver

logging:
  file: logs/application.log
  level:
    org.springframework.boot: INFO
    org.springframework.web: INFO
    org.springframework.data: DEBUG
    kr.sir: DEBUG
    
path: 
  fileName: ../webapps/ROOT/WEB-INF/classes/config.yml