service:
  info:
    name: jsboard
    version: 1.0.0
    
logging:
  level:
    org.springframework.boot: INFO
    org.springframework.web: DEBUG
    org.springframework.data: INFO
    
spring:
  mvc:
    view:
      prefix: /WEB-INF/jsp/
      suffix: .jsp    
  thymeleaf:
    cache: false
  jpa:
    show-sql: true
    
    hibernate:
      ddl-auto: update

  datasource:
     initialize: true
#     url: jdbc:h2:tcp://localhost/~/test;MVCC=TRUE
     url: jdbc:mysql://ahn13.gnutest.com:3306/ahn13?
     username: ahn13
     password: qwer
     driver-class-name: com.mysql.jdbc.Driver


#logging:
#  level:
#    org.springframework.web: INFO