table:
  prefix: js_

---

spring:
  profiles: local-g
  mvc:
    view:
      prefix: /WEB-INF/jsp/
      suffix: .jsp    
  thymeleaf:
    cache: false
  jpa:
    show-sql: true
    database: mysql
    hibernate:
      ddl-auto: create
      naming:
        physical-strategy: kr.sir.common.PrefixNamingStrategy

  datasource:
     initialize: true
     url: "jdbc:mysql://localhost:3306/sirgjw?characterEncoding=utf8&useSSL=false"
     username: "root"
     password: "8989"
     driver-class-name: com.mysql.jdbc.Driver
     
logging:
  file: logs/application.log
  level:
    org.springframework.boot: INFO
    org.springframework.web: INFO
    org.springframework.data: DEBUG
  
---

spring:
  profiles: local-a
  mvc:
    view:
      prefix: /WEB-INF/jsp/
      suffix: .jsp    
  thymeleaf:
    cache: false
  jpa:
    show-sql: true
    database: mysql
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: kr.sir.common.PrefixNamingStrategy

  datasource:
     initialize: true
     url: "jdbc:mysql://localhost:3306/ahn?characterEncoding=utf8&useSSL=false"
     username: "ahn23"
     password: "qwer"
     driver-class-name: com.mysql.jdbc.Driver
     
logging:
  file: logs/application.log
  level:
    org.springframework.boot: INFO
    org.springframework.web: INFO
    org.springframework.data: DEBUG

---

spring:
  profiles: test
  mvc:
    view:
      prefix: /WEB-INF/jsp/
      suffix: .jsp    
  thymeleaf:
    cache: false
  jpa:
    show-sql: true
    
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: kr.sir.model.module.PrefixNamingStrategy

  datasource:
     initialize: true
     url: jdbc:mysql://ahn13.gnutest.com:3306/ahn13
     username: ahn13
     password: qwer
     driver-class-name: com.mysql.jdbc.Driver

logging:
  file: logs/application.log
  level:
    org.springframework.boot: INFO
    org.springframework.web: DEBUG
    org.springframework.data: INFO
    
---
spring:
  profiles: logging-daily
logging:
  config: classpath:logback-spring.xml    