table:
  prefix: js1_
  
spring:
  mvc:
    view:
      prefix: /WEB-INF/jsp/
      suffix: .jsp
  thymeleaf:
    cache: false
  jpa:
    show-sql: true
    database: mysql
    hibernate:
      ddl-auto: none
      naming:
        physical-strategy: kr.sir.common.PrefixNamingStrategy

---

spring:
  profiles: local-g
  datasource:
     initialize: true
     url: "jdbc:mysql://localhost:3306/sirgjw?characterEncoding=utf8&useSSL=false&zeroDateTimeBehavior=convertToNull"
     username: "root"
     password: "8989"
     driver-class-name: com.mysql.jdbc.Driver
     
logging:
  file: logs/application.log
  level:
    org.springframework.boot: INFO
    org.springframework.web: INFO
    org.springframework.data: DEBUG
  
---

spring:
  profiles: local-a
  datasource:
     initialize: true
     url: "jdbc:mysql://localhost:3306/ahn?characterEncoding=utf8&useSSL=false&zeroDateTimeBehavior=convertToNull"
#     url: "jdbc:mysql://localhost:3316/ahn?characterEncoding=utf8&useSSL=false&zeroDateTimeBehavior=convertToNull"
     username: "ahn23"
     password: "qwer"
     driver-class-name: com.mysql.jdbc.Driver
     
logging:
  file: logs/application.log
  level:
    org.springframework.boot: INFO
    org.springframework.web: INFO
    org.springframework.data: DEBUG

---

spring:
  profiles: cafe24-test
  datasource:
     initialize: true
     url: "jdbc:mysql://localhost:3306/sirjsp?characterEncoding=utf8&useSSL=false&zeroDateTimeBehavior=convertToNull"
#     url: "jdbc:mysql://sirjsp.cafe24.com:3306/sirjsp?characterEncoding=utf8&useSSL=false&zeroDateTimeBehavior=convertToNull"
     username: sirjsp
     password: sirjsp12
     driver-class-name: com.mysql.jdbc.Driver

logging:
  file: logs/application.log
  level:
    org.springframework.boot: INFO
    org.springframework.web: INFO
    org.springframework.data: DEBUG
    
---

spring:
  profiles: logging-daily
  
logging:
  config: classpath:logback-spring.xml    